# Generated by Django 4.1.2 on 2022-10-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('pid', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=20)),
                ('price', models.FloatField()),
                ('weight', models.FloatField()),
                ('category', models.CharField(max_length=25)),
                ('delivery', models.SmallIntegerField(default=7)),
                ('in_stock', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='upload')),
            ],
        ),
    ]
