# Generated by Django 4.1.2 on 2022-11-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_alter_product_deliverycharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(default=10),
        ),
    ]
