# Generated by Django 4.1.2 on 2022-11-06 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productapp', '0002_alter_product_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0.0)),
                ('ordered', models.BooleanField(default=False)),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productapp.product')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
