# Generated by Django 4.1.2 on 2022-11-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='deliveryCharge',
            field=models.IntegerField(default=0.0),
        ),
    ]
