# Generated by Django 4.1.2 on 2022-11-06 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('oid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=1)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('addr', models.TextField(max_length=100)),
                ('town', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=14)),
                ('comment', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('In Stock', 'In Stack'), ('Out of Stock', 'Out of Stock')], default='Pending', max_length=50)),
                ('cartitem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cartitem')),
            ],
        ),
    ]
